# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


  target 'estimoteProject' do
    pod 'EstimoteProximitySDK', '~> 1.0'
  end
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for estimoteProject


  target 'estimoteProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end


target 'estimoteProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for estimoteProject-tvOS

  target 'estimoteProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
